from enum import Enum 

class ResponseSignal(Enum):
    FILE_TYPE_NOT_SUPPORTED ="FILE_TYPE_NOT_SUPPORTED"
    FILE_SIZE_EXCEEDED = "FILE_SIZE_EXCEEDED"
    SUCCESS = "SUCCESS"
    FILE_NOT_FOUND = "FILE_NOT_FOUND"
    FILE_ALREADY_EXISTS = "FILE_ALREADY_EXISTS"
    FILE_NOT_SAVED = "FILE_NOT_SAVED"
    FILE_NOT_DELETED = "FILE_NOT_DELETED"
    FILE_NOT_UPDATED = "FILE_NOT_UPDATED"
    FILE_NOT_READ = "FILE_NOT_READ"
    FILE_NOT_WRITTEN = "FILE_NOT_WRITTEN"
    FILE_NOT_COPIED = "FILE_NOT_COPIED"
    FILE_NOT_MOVED = "FILE_NOT_MOVED"
    FILE_NOT_RENAMED = "FILE_NOT_RENAMED"
    FILE_UPLOAD_FAILED = "FILE_UPLOAD_FAILED"
    FILE_UPLOADED_SUCCESSFULLY = "FILE_UPLOADED_SUCCESSFULLY"    
    PROCESSING_FAILED = "PROCESSING_FAILED"
    PROCESSING_SUCCESSFULLY = "PROCESSING_SUCCESSFULLY"
    NO_FILE_FOUND_IN_PROJECT = "NO_FILE_FOUND_IN_PROJECT"
    FILE_ID_NOT_FOUND = "FILE_ID_NOT_FOUND"
    PROJECT_NOT_FOUND_ERROR = "PROJECT_NOT_FOUND_ERROR"
    INSERT_INTO_VECTORDB_FAILED = "INSERT_INTO_VECTORDB_FAILED"
    INSERT_INTO_VECTORDB_SUCCESSFULLY = "INSERT_INTO_VECTORDB_SUCCESSFULLY"

    VECTORDB_COLLECTION_RETREIVED_SUCCESSFULLY = "VECTORDB_COLLECTION_RETREIVED_SUCCESSFULLY"
    VECTORDB_COLLECTION_RETREIVED_FAILED = "VECTORDB_COLLECTION_RETREIVED_FAILED"

    SEARCH_VECTORDB_SUCCESSFULLY = "SEARCH_VECTORDB_SUCCESSFULLY"
    SEARCH_VECTORDB_FAILED = "SEARCH_VECTORDB_FAILED"

    ANSWER_RAG_FAILED = "ANSWER_RAG_FAILED"
    ANSWER_RAG_SUCCESSFULLY = "ANSWER_RAG_SUCCESSFULLY"